Image viewer brightness control
dials/dials pull request #1774
Opened 2021-06-30 18:29 UTC by dagewa

There may be different opinions about this, but I find the `dials.image_viewer` brightness to usually start too dark, to step too much on clicking in the scroll bar, and all the useful range being up the left end of the scale. This PR adjusts defaults to improve things a little. I welcome other views.

2021-07-01 08:35 UTC, dagewa commented
I think we can do better. I'll try a non-linear function when I get some time.

2021-07-06 11:39 UTC, ndevenish commented
![image](https://user-images.githubusercontent.com/529963/124594008-348b5680-de57-11eb-9958-f50eb3fe5264.png)

2021-07-06 11:45 UTC, ndevenish commented
This seems to lose a lot of the controllability and maximum contrast. The selector (running via NX to diamond) seems only to "jump" when dragging between 1, 2, 6, 10, 14, 18, 22, 26, 30 making it darker, and a similar but slightly different range when dragging lighter. Fast-dragging frustratingly seems to allow spaces in-between.

In addition, it seems to lose a lot of the maximum contrast end:
![image](https://user-images.githubusercontent.com/529963/124594660-fb071b00-de57-11eb-9ea2-2ea9f93a51a5.png)

I feel that it should definitely allow you to make it "Darker" than is useful, because then you can see the extreme ends and drag somewhere in the middle.

2021-07-06 12:24 UTC, dagewa commented
Thanks for the comments. I found the dark end of the scale fairly useless, so I cut it back earlier, but I can certainly extend it darker again. I'm not sure about the jumping behaviour. I don't think I saw that locally, but I'll investigate

2021-07-06 12:38 UTC, ndevenish commented
Actually, the behaviour that I'm observing is that it's not moving until I'm off the edge of the handle. This might be a specific linux/wx interaction problem


https://user-images.githubusercontent.com/529963/124601163-6bfe0100-de5f-11eb-84ef-0053a2ad4dd0.mp4

2021-07-06 12:49 UTC, dagewa commented
Ah right, actually I see the same. I had taken to clicking in the bar either side of the button, which steps by +/- 2

2021-08-09 11:44 UTC, graeme-winter requested changes
I am not certain I fully agree with the changes in here - while the "slider" is integral it becomes very hard to find good values with the changes in this PR for a stack of 10 images

The newly nonlinear nature of the scaling is to me troublesome... but I am not sure what to suggest in its place

Please could you try it out yourself with a stack of 10 images then see how you feel about the use of dynamic range (hint: only the left hand extreme of the slider is useful)

2021-08-09 11:44 UTC, graeme-winter commented on command_line/image_viewer.py
> +brightness = 20
Approve of this change (though personally I would have set 10)

2021-08-09 11:44 UTC, graeme-winter commented on newsfragments/1774.feature
> +``dials.image_viewer``: adjust brightness control for better defaults.
Better is an opinion, would say they are certainly better for photon counting detectors

2021-08-09 11:47 UTC, graeme-winter commented
> I am not certain I fully agree with the changes in here - while the "slider" is integral it becomes very hard to find good values with the changes in this PR for a stack of 10 images
> 
> The newly nonlinear nature of the scaling is to me troublesome... but I am not sure what to suggest in its place
> 
> Please could you try it out yourself with a stack of 10 images then see how you feel about the use of dynamic range (hint: only the left hand extreme of the slider is useful)

In fairness, this accusation should also be levelled at the existing implementation

2021-08-09 14:46 UTC, dagewa commented
It still looks a lot better to me :thinking:

**Main `stack=1`**
![main-stack-1](https://user-images.githubusercontent.com/11502083/128725375-5bc4075a-4e4d-4862-b14d-5776394be662.png)

**Branch `stack=1`**
![branch-stack-1](https://user-images.githubusercontent.com/11502083/128725493-ab5cdbf4-e5fe-4c24-a041-49bc1ef8075f.png)

Neither very much use, but I can at least start to see diffraction spots on the branch

**Main `stack=10`**
![main-stack-10](https://user-images.githubusercontent.com/11502083/128725429-50f97e43-b248-43af-bf8e-d01a9a99e1e2.png)

**Branch `stack=10`**
![branch-stack-10](https://user-images.githubusercontent.com/11502083/128725535-e30884a3-533b-4dcc-bfff-816ad419950b.png)

The branch behaviour is _much_ better in this case. On main it's just a dark mess. On the branch I get a clean diffraction image.

2021-08-13 11:42 UTC, dagewa commented
@graeme-winter I've been discussing this with @ndevenish. I'm not able to reproduce anything concerning with the example I tried, so could you please provide an example to illuminate your request for changes? Thanks

2021-08-13 11:42 UTC, ndevenish commented
Since there's lack of consensus on this now we'll leave for this release.

2022-03-09 10:03 UTC, closed without merging